apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sparks.ibm.com
spec:
  group: ibm.com
  names:
    kind: Spark
    listKind: SparkList
    plural: sparks
    singular: spark
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
