apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demo-operators-view-ep
  labels:
    olm.opgroup.permissions/aggregate-to-view: demo-operators
rules:
- apiGroups:
  - packages.operators.coreos.com
  resources:
  - packagemanifests
  verbs:
  - get
  - list
  - watch
