apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: spark-operator
roleRef:
  kind: ClusterRole
  name: spark-operator
subjects:
  - kind: ServiceAccount
    name: spark-operator
    namespace: dday2019
